weights: storage/weights/model-latest.pt

task:
  name: classification
  classes: [name, position, company, address, mail, tel, web, tax]

backbone:
  replace_word_embeddings: vinai/phobert

head:
  head_size: 256
