version: "3.7"

services:
  spade_dev_env:
    image: spade-dev:latest
    build:
      context: ..
      dockerfile: .docker/Dockerfile
    container_name: spade-dev
    entrypoint: sleep 1000000
    volumes:
      - ..:/workspace/
    ports:
      - 8501:8501
      - 8000:8000
